### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webxr-ios-js#48]
I think we should clean up the code. Currently the code looks a bit dirty and readers may think it isn't ready yet. For example it has

* Inconsistent coding style
* Inconsistent indentation, hard tabs or soft tabs. And some of the indentations are broken
* Out date comment
* Lack of comments
* etc.

**Comment by takahirox** [comment]
Yeah, agreed. We should also clean up them. BTW could you elaborate approaches for me please?

**Comment by blairmacintyre** [comment]
not sure what you mean by "elaborate approaches"

**Comment by takahirox** [comment]
Sorry I wrote poorly. What different approaches are used now? I'm still a new to src/arkit/* source codes.

**Comment by takahirox** [comment]
I made #49, #50, #51, #52. I'll close this issue if they're merged. Let's open another PR for further cleaning up/refactoring if needed.

**Comment by takahirox** [comment]
Closing because they're merged.
