### ISSUE TITLE
Support the newest hit test API

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webxr-ios-js#53]
From #33

Currently we support [old hit test API](https://github.com/immersive-web/anchors/blob/master/explainer.md). We should support [the newest one](https://github.com/immersive-web/hit-test/blob/master/hit-testing-explainer.md).

And [the old explainer seems being out dated soon](https://github.com/immersive-web/hit-test/pull/55).

**Comment by joshmarinacci** [comment]
Is the hit test api part of WebXR 1.0 or a later module?

**Comment by takahirox** [comment]
Not sure, but I guess a later module.

What I know is AR module repository https://github.com/immersive-web/webxr-ar-module is separated from WebXR API core repository. And hit test API is sub module of AR module.

**Comment by joshmarinacci** [comment]
k. then i guess we can wait for later for this.

**Comment by blairmacintyre** [comment]
So, in general, I think it would be VERY PREFERABLE if we update to follow these repositories as we can.  For two reasons:
- we'll be closer to the eventual goal
- we'll be able to give feedback on the APIs and how we think they will work.

That applies to hit test, anchors, real-world-geometry, dom overlay, lighting estimation ... essentially, all the ones we are already implementing!

**Comment by takahirox** [comment]
Agreed with Blair.

And as I wrote the above, the old hit test API we currently support seems being out dated soon. If we release with the old one
- user may think we don't aggressively follow the newer APIs
- if our users write an application following the old API they need to update their code when hit test API is fixed and released

(Of course the problem is our limited time tho!)

**Comment by takahirox** [comment]
Closing in favor of #82
