### ISSUE TITLE
Some limitations on shim

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webxr-ios-js#58]
From #34 

shim asynchronously loads the entire webxr-polyfill.js on demand when `navigator.xr.requestSession()` is invoked

```javascript
navigator.xr.isSessionSupported('immersive-ar').then(supported => {
  if (supported) {
    navigator.xr.requestSession('immersive-ar').then(session => { // the entire polyfill file is loaded
      ...
    });
  }
});
```

So there are some limitations compared to the native WebXR API support. A limitation I'm aware of is `XR*` aren't defined until the entire webxr-polyfill.js is loaded. For example the following user code judges that the browser with shim doesn't support WebXR API.

```javascript
const supportsWebXR = (window.XR !== undefined);
if (supportsWebXR) {
  // browser supports WebXR API so going forward
  navigator.xr.isSessionSupported(...).then(supported => {
    if (supported) {
      navigator.xr.requestSession(...).then(session => {
        ...
      });
    }
  });
} else {
  // browser doesn't support WebXR API so stopping with error message
  console.error('Your browser doesn\'t seem to support WebXR');
}
```

There may be other limitations.

Perhaps shim works fine for most of general use cases so accepting such limitations may be an easy solution.

**Comment by blairmacintyre** [comment]
Hmmm, I didn't look closely enough at this.  When @joshmarinacci and I originally discussed this idea, the goal was to include the functions that are needed before a session is created, like `isSessionSupported`, in the shim.  I don't think it's feasible to have acceptable workflows fail.

**Comment by takahirox** [comment]
Yeah I think the goal looks good to me. And shim should work fine for most of general use cases. Only tricky and (maybe) rare use cases may fail as I posted the example code above.

Writing a note about such limitations in the WebXR viewer doc or somewhere may be helpful to users and devs, and I guess it may be good enough.

Any thoughts @joshmarinacci ?

**Comment by joshmarinacci** [comment]
The shim should create a temporary xr object so that this case won’t fail

**Comment by takahirox** [comment]
Does "xr object" mean `navigator.xr`? If so, it isn't what I care about. What I'm pointing out is

```javascript
const supportsWebXR = (window.XR !== undefined);
```

in the example code. This line is executed before calling `navigator.xr.requestSession()` so `XR` isn't defined because the polyfill isn't loaded yet at that time. Then `supportsWebXR` will be `false` and the application ends up judging that the browser with shim doesn't support WebXR API.

**Comment by joshmarinacci** [comment]
Hmm. What does the spec say? Should window.XR exist?

**Comment by takahirox** [comment]
Yes.

https://www.w3.org/TR/webxr/#xr-interface

> Exposed=Window

**Comment by joshmarinacci** [comment]
Hmm. You're right. We need window.XR. But it's not clear what that object should be. Is it just another copy of navigator.xr?

**Comment by takahirox** [comment]
My understanding is WebXR API implementation should declare `XR*` (XR, XRSession, XRWebGLLayer, and so on) classes and expose them in window(global) scope.

Not only XR, but also XRSession, XRWebGLLayer, and other interface definitions are with "Exposed=Window"

https://www.w3.org/TR/webxr/#xrsession-interface
https://www.w3.org/TR/webxr/#xrwebgllayer-interface

Actually XRWebGLLayer can be instanciated in user code (meaning application code, JS 3D engine code, or so) with `new XRWebGLLayer(...)`. [For example in Three.js](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webvr/WebXRManager.js#L139)

So, `window.XR` is accessing `XR` class. `window.XR !== undefined` is checking if XR class is declared.

**Comment by takahirox** [comment]
Closing in favor of #60. But we have other limitations now. We open other issues for them.
