### ISSUE TITLE
XRRigidTransform should be able to be instanciated even before starting session

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webxr-ios-js#61]
From #60.

We updated shim to expose XR* classes to resolve the limitation pointed out in #58. But it still has another limitation.

* `XRRigidTransform` should be able to be instanciated by user even before starting session but the current shim prohibits

Perhaps we can work around this limitation with [the idea mentioned here](https://github.com/MozillaReality/webxr-ios-js/pull/60#issuecomment-547137755) tho the code could be a bit mess.

**Comment by joshmarinacci** [comment]
don't support this for now.
