### ISSUE TITLE
Extending WebXR API before starting session is problematic

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webxr-ios-js#63]
From https://github.com/MozillaReality/webxr-ios-js/pull/60#issuecomment-547156660

Extending XR* classes by user before starting session is problematic on the current shim.

1. Adding methods like we webxr-ios-js do

```javascript
XRSession.prototype.extra_method = function () {
  ...
};
```

2. Extending class (not sure if extending XR* makes sense but it should be able to do)

```javascript
class CustomXRSession extends XRSession {
  ...
}
```

They extend old fake XR* classes as probably user unexpects.

1. can be tracked and we can reflect to new XR* [like this](https://github.com/MozillaReality/webxr-ios-js/pull/60#issuecomment-547193256) maybe? But perhaps no solution for 2.?

Another question is, should we really take care about these hacky and rare use cases?

**Comment by joshmarinacci** [comment]
For now we should say these are unsupported cases.

**Comment by blairmacintyre** [comment]
I am starting to think this is going to be a show stopper ... when even the simple samples trigger these problems, I worry that realistic examples will be worse.
