### ISSUE TITLE
Three.js WebXR AR examples don't recognize our WebXR API

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webxr-ios-js#80]
[Three.js WebXR AR examples](https://threejs.org/examples/?q=webxr) don't recognize our AR capability. When the application starts up Three.js `ARButton` checks `navigator.xr` but at that time it seems `navigator.xr` isn't defined yet.

Android Chrome (native WebXR API) and [WebXR Emulator Extension](https://github.com/MozillaReality/WebXR-emulator-extension) work fine. So maybe there is something problem in our side.

**Comment by takahirox** [comment]
There seems being the same problem on Google's [&lt;model-viewer&gt;](https://modelviewer.dev/examples/augmented-reality.html) (because I guess it's built on Three.js?)

**Comment by blairmacintyre** [comment]
are we not definitely navigator.xr in the shim?  Didn't something change to navigator.XR or something?  (fuzzy memory here)

**Comment by takahirox** [comment]
I need to investigate but I guess somehow WebXR API detection with navigator.xr is somehow done before loading shim. When is shim exactly loaded?

**Comment by blairmacintyre** [comment]
That's not possible or shouldn't be.  The shim is loaded using the WkWebView feature that preloads some JS before loading the page.  Are you sure the shim that's bundled with xcode is actually setting .xr and not something else like .XR?

**Comment by takahirox** [comment]
Yes, navigator.xr.

I'll investigate closer today.

**Comment by takahirox** [comment]
I found an interesting fact.

1. https://threejs.org/examples/#webxr_ar_paint
2. https://threejs.org/examples/webxr_ar_paint.html

They are the same Three.js AR paint example. Our WebXR API is recognized in 2. while it isn't in 1.

The difference is whether using &lt;iframe&gt;. 2. is the WebXR AP paint example itself and 1. opens 2. in &lt;iframe&gt;.

I set break point in the example in 1 and realized that `navigator.xr` doesn't seem to be defined in &lt;iframe&gt;.

So my speculation is the shim has no effect to a page loaded in &lt;iframe&gt;. Can this likely happen from the view of preloading with WkWebView?

**Comment by blairmacintyre** [comment]
Yes, that could definitely be the case.  

Is webxr supposed to work in iFrames?  A subset of it?  Seems dangerous.

**Comment by joshmarinacci** [comment]
I seem to recall us discussing webxr in iframes about a year ago. I think we agreed to have some property set on the iframe to enable it.

**Comment by takahirox** [comment]
From Three.js html code

```
&gt;iframe id="viewer" name="viewer" allowfullscreen allowvr onmousewheel=""&lt;
```

It has `allowvr` (not "xr" tho), is this what @joshmarinacci pointed out?

**Comment by takahirox** [comment]
And, I'm not familiar with WebKit at all. Is technically possible to preload the shim even in &lt;iframe&gt;?

**Comment by blairmacintyre** [comment]
> It has `allowvr` (not "xr" tho), is this what @joshmarinacci pointed out?

Probably.  

> And, I'm not familiar with WebKit at all. Is it technically possible to preload the shim even in <iframe>?

I _think_ so but I can't remember, nor remember how.

**Comment by kearwood** [comment]
> I seem to recall us discussing webxr in iframes about a year ago. I think we agreed to have some property set on the iframe to enable it.

WebXR uses feature policy to enable or disable it in iframes:

https://immersive-web.github.io/webxr/#feature-policy

In particular, “xr-spatial-tracking”.

**Comment by takahirox** [comment]
Thanks @kearwood. My understanding is if `xr-spatial-tracking` attribute isn't specified `navigator.xr` should be defined but `isSessionSupported('immersive-vr/ar')` should return false and `requestSession('immersive-vr/ar')` should fail, correct?

If it's correct, we need to request firefox-ios to load the shim even in iframe.

I guess we can't know iframe attribute from inside of iframe. Then we add another shim for `xr-spatial-tracking` disabled case and firefox-ios preloads an appropriate one depending on iframe attribute?

**Comment by blairmacintyre** [comment]
Let's leave this open for now and investigate

**Comment by takahirox** [comment]
Let's ask Firefox iOS team about how we should do, and update if needed later.

**Comment by takahirox** [comment]
I had a comment from firefox-ios team

> Look for where your script is injected using WKUserScript constructor. That takes an argument forMainFrameOnly , a boolean, set that to false.

I did it and our WebXR API is recognized even in a web page in iframe. But I face another error.

```
ReferenceError: Can't find variable: arkitCallback_initAR_1588968895079_942515975864898
```

I guess the bridge between a web page in iframe and arkit doesn't work. I'm not familiar with the bridge yet but does my guess sound correct? And anyone knows how to resolve?

**Comment by blairmacintyre** [comment]
Ah, of course.  iFrames can't talk to the native app.  It can only talk to the parent of the frame (the page), I believe.

If we want to enable iFrames we have to do this in the shim:
- detect that we're in an iframe
- instead of calling the native hooks, send messages to the parent frame
- in our main page shim, look for those messages, and relay them to the native app
- in our main page shim, look for replies/message from native, and relay them to the iframe

This will be a non-trivial amount of work;  straightforward I think, but still not trivial.

We'll also need the page to keep track of multiple iFrames (e.g., only one can create an immersive session at a time, and we need to relay the data to the right one).
