### ISSUE TITLE
Follow the newest Anchor API specification

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/webxr-ios-js#93]
WebXR Anchor API seems to be finalized soon. We should update our Anchor API to follow the newest spec once it lands.

https://immersive-web.github.io/anchors/

**Comment by blairmacintyre** [comment]
It's still got a bit of churn left.  Soon, though, yes.

**Comment by takahirox** [comment]
Yeah, I know at least one long ongoing discussion thread there. So "once it lands".
